# Generated by Django 6.0.5 on 2026-08-26 14:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipped_app', '0007_alter_subject_code_no_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='final_exam_score',
            field=models.FloatField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='is_at_risk',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='performance_label',
            field=models.CharField(blank=True, choices=[('High', 'High Performer'), ('Medium', 'Medium Performer'), ('Low', 'Low Performer'), ('At-Risk', 'At-Risk Student')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='predicted_label',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='predicted_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'date'], name='flipped_app_subject_5bd000_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['subject', 'is_at_risk'], name='flipped_app_subject_d0fa46_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['predicted_label'], name='flipped_app_predict_3137f3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['final_exam_score'], name='flipped_app_final_e_dac02f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['student', 'subject'], name='flipped_app_student_6dc9fb_idx'),
        ),
    ]
